import type {Contact, Message, Workflow, Job, Company} from '../types';

export const mockContacts: Contact[] = [
    {
        id: '1',
        companyId: 'company-1',
        name: 'John Doe',
        phone: '+1 234 567 8900',
        email: 'john@example.com',
        tags: ['VIP', 'Marketing'],
        consentStatus: 'granted',
        optOutChannels: [],
    },
    {
        id: '2',
        companyId: 'company-1',
        name: 'Jane Smith',
        phone: '+1 234 567 8901',
        email: 'jane@example.com',
        tags: ['Support'],
        consentStatus: 'granted',
        optOutChannels: ['sms'],
    },
    {
        id: '3',
        companyId: 'company-1',
        name: 'Bob Wilson',
        phone: '+1 234 567 8902',
        email: 'bob@example.com',
        tags: ['Sales'],
        consentStatus: 'pending',
        optOutChannels: [],
    },
];

export const mockMessages: Message[] = [
    {
        id: '1',
        companyId: 'company-1',
        contactId: '1',
        channel: 'sms',
        direction: 'outbound',
        body: 'Hello! How are you?',
        status: 'delivered',
        sentAt: new Date(Date.now() - 3600000).toISOString(),
    },
    {
        id: '2',
        companyId: 'company-1',
        contactId: '2',
        channel: 'email',
        direction: 'outbound',
        subject: 'Meeting Reminder',
        body: 'Your meeting is scheduled for 3 PM',
        status: 'sent',
        sentAt: new Date(Date.now() - 7200000).toISOString(),
    },
    {
        id: '3',
        companyId: 'company-1',
        contactId: '1',
        channel: 'sms',
        direction: 'inbound',
        body: 'Thanks for reaching out! I have a question.',
        status: 'delivered',
        sentAt: new Date(Date.now() - 5400000).toISOString(),
    },
    {
        id: '4',
        companyId: 'company-1',
        contactId: '3',
        channel: 'sms',
        direction: 'inbound',
        body: 'Can I get more information about your services?',
        status: 'delivered',
        sentAt: new Date(Date.now() - 9000000).toISOString(),
    },
    {
        id: '5',
        companyId: 'company-1',
        contactId: '2',
        channel: 'sms',
        direction: 'outbound',
        body: 'Your order has been shipped! Track it here: example.com/track',
        status: 'delivered',
        sentAt: new Date(Date.now() - 10800000).toISOString(),
    },
    {
        id: '6',
        companyId: 'company-1',
        contactId: '1',
        channel: 'email',
        direction: 'inbound',
        subject: 'Re: Meeting Reminder',
        body: 'Thank you! I will be there.',
        status: 'delivered',
        sentAt: new Date(Date.now() - 14400000).toISOString(),
    },
    {
        id: '7',
        companyId: 'company-1',
        contactId: '3',
        channel: 'sms',
        direction: 'outbound',
        body: 'Special offer: 20% off your next purchase!',
        status: 'sent',
        sentAt: new Date(Date.now() - 18000000).toISOString(),
    },
    {
        id: '8',
        companyId: 'company-1',
        contactId: '2',
        channel: 'sms',
        direction: 'inbound',
        body: 'Yes, I would like to schedule an appointment.',
        status: 'delivered',
        sentAt: new Date(Date.now() - 21600000).toISOString(),
    },
];

export const mockWorkflows: Workflow[] = [
    {
        id: '1',
        companyId: 'company-1',
        name: 'Welcome Campaign',
        description: 'Automated welcome series for new contacts',
        status: 'active',
        version: 2,
        definition: {},
    },
    {
        id: '2',
        companyId: 'company-1',
        name: 'Abandoned Cart',
        description: 'Re-engagement for abandoned carts',
        status: 'active',
        version: 1,
        definition: {},
    },
    {
        id: '3',
        companyId: 'company-1',
        name: 'Birthday Messages',
        description: 'Automated birthday wishes',
        status: 'paused',
        version: 1,
        definition: {},
    },
];

export const mockJobs: Job[] = [
    {
        id: '1',
        companyId: 'company-1',
        type: 'Bulk SMS Send',
        status: 'running',
        progress: 67,
        startedAt: new Date(Date.now() - 1800000).toISOString(),
    },
    {
        id: '2',
        companyId: 'company-1',
        type: 'Contact Import',
        status: 'completed',
        progress: 100,
        startedAt: new Date(Date.now() - 7200000).toISOString(),
        finishedAt: new Date(Date.now() - 6900000).toISOString(),
    },
];

export const mockCompanies: Company[] = [
    {
        id: 'company-1',
        name: 'Acme Corp',
        status: 'active',
        createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    },
    {
        id: 'company-2',
        name: 'TechStart Inc',
        status: 'active',
        createdAt: new Date(Date.now() - 86400000 * 60).toISOString(),
    },
];
